//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLoginPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersList
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Username { get; set; }
        public string eMail { get; set; }
        public System.DateTime birthDate { get; set; }
        public byte gender { get; set; }
        public string password { get; set; }
    }
}
